require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/fixtures/**/*'

# Disable Capybara and FactoryBot cops (not used in this project)
# These are loaded as dependencies of rubocop-rspec but aren't applicable
RSpec/Capybara:
  Enabled: false

RSpec/FactoryBot:
  Enabled: false

RSpec/Rails:
  Enabled: false

RSpecRails/HaveHttpStatus:
  Enabled: false  # Not using Rails, using Sinatra with Rack::Test

Capybara/RSpec/PredicateMatcher:
  Enabled: false

# Style preferences aligned with existing codebase
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

# Metrics - reasonable limits for this codebase
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'api/app.rb'
    - 'bin/*'

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'bin/*'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'bin/*'
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'bin/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'bin/*'

# Layout preferences
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# RSpec-specific
RSpec/ExampleLength:
  Max: 70  # Integration tests can be long

RSpec/MultipleExpectations:
  Max: 20  # Integration tests need multiple expectations

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Enabled: false  # Allow flexible context descriptions

RSpec/DescribeClass:
  Enabled: false  # Allow describing features/integrations

RSpec/AnyInstance:
  Enabled: false  # Sometimes necessary for testing

RSpec/SubjectStub:
  Enabled: false  # Allow stubbing sleep and other methods

RSpec/VerifiedDoubles:
  Enabled: false  # Normal doubles are fine for simple cases

# Disable overly strict cops
Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
